#cloud-config
ssh_pwauth: no

users:
  - name: $USER_NAME
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    shell: /bin/bash
    ssh_authorized_keys:
      - $SSH_KEY

write_files:
  - path: "/usr/local/etc/startup.sh"
    permissions: "755"
    content: |
      #!/bin/bash

      zypper refresh
      zypper install -y nginx

      mkdir -p /srv/www/htdocs
      echo "Welcome to our server" > /srv/www/htdocs/index.html
      sed -i -- "s/Welcome to our server/ Yandex Cloud - $HOSTNAME/" /srv/www/htdocs/index.html || true

      systemctl enable nginx --now
    defer: true

runcmd:
  - ["/usr/local/etc/startup.sh"]

packages:
  - yq
